# Generated by Django 2.0.6 on 2018-06-23 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, max_length=255)),
                ('size', models.CharField(choices=[('S', 'standard'), ('M', 'mini'), ('B', 'big'), ('R', 'bridge'), ('Q', 'squared')], max_length=1)),
                ('same_reverse', models.BooleanField(default=True)),
                ('front_border_color', models.CharField(default='#000000', max_length=7)),
                ('front_cut_marks_color', models.CharField(default='#FF0000', max_length=7)),
                ('back_border_color', models.CharField(default='#000000', max_length=7)),
                ('back_cut_marks_color', models.CharField(default='#FF0000', max_length=7)),
                ('cards', models.TextField()),
                ('front_layers', models.TextField()),
                ('back_layers', models.TextField()),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, max_length=255)),
                ('owners', models.ManyToManyField(related_name='games', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='deck',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decks', to='designer.Game'),
        ),
    ]
