# Generated by Django 2.0.6 on 2018-07-16 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0003_auto_20180716_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='back_layers',
            field=models.TextField(default='{}'),
        ),
        migrations.AlterField(
            model_name='deck',
            name='cards',
            field=models.TextField(default='{}'),
        ),
        migrations.AlterField(
            model_name='deck',
            name='front_layers',
            field=models.TextField(default='{}'),
        ),
    ]
