# Generated by Django 2.0.6 on 2018-07-16 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0004_auto_20180716_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='portrait',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='deck',
            name='back_layers',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='deck',
            name='cards',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='deck',
            name='front_layers',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='deck',
            name='size',
            field=models.CharField(choices=[('PO', 'estandar poker 63x88'), ('B1', 'bridge 56x88'), ('B1', 'bridge 57x89'), ('M1', 'mini 41x68'), ('M2', 'mini 45x68'), ('M3', 'mini 44x63'), ('C1', 'cuadrada 68x68'), ('C2', 'cuadrada 70x70'), ('TA', 'tarot 70x110'), ('GR', 'grande 70x120')], max_length=2),
        ),
    ]
